### PR TITLE
Introduce FlutterStreamsChannel to allow multiple anchoredObjectQueries

### PR DESCRIPTION
**Pull request by opsb**
## Status
READY

## Migrations
NO

## Description
Fixes https://github.com/VictorKachalov/health_kit_reporter/issues/20 by introducing https://pub.dev/packages/streams_channel to handle multiple streams over the `health_kit_reporter_event_channel_anchored_object_query` channel.

## Notes
This issue likely affects all of the channels registered using `FlutterEventChannel`. If you're happy with the approach you can just swap in `FlutterStreamsChannel` for each `FlutterEventChannel`.

### CODE REVIEW

**Comment by opsb** [comment]
I think there may be an issue with this implementation when the anchored query is running in the background. Haven't confirmed yet and will dig in some more tomorrow.

**Comment by VictorKachalov** [comment]
Hi @opsb 

Thank you for your PR. A small question. Does this package "streams_channels" support null-safety (Flutter 2.0) ?

**Comment by opsb** [comment]
@VictorKachalov doesn't look like it https://pub.dev/packages/streams_channel, hasn't been updated in 14months

**Comment by VictorKachalov** [comment]
ok, the thing is, that the PR uses quite old package, I can not guarantee the normal workflow for users with null safety (actual now - 1.3.0). I will provide additional version 1.1.1 for not nullsafety users

**Pull request merged**
